language: objective-c

branches:
 only:
 - master

xcode_project: DCKitSample.xcodeproj
xcode_scheme: DCKitSample
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

script:
- xcodebuild clean build test -project DCKitSample.xcodeproj -scheme DCKitSample -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
